# Generated by Django 5.0.7 on 2024-07-23 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=1000)),
                ("listing_id", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("check_in", models.CharField(max_length=10)),
                ("check_out", models.CharField(max_length=10)),
                ("adults", models.IntegerField()),
                ("children", models.IntegerField()),
                ("infants", models.IntegerField()),
                ("pets", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
