# Generated by Django 5.0.7 on 2024-07-30 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="adults",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="check_in",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="check_out",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="children",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="infants",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="pets",
        ),
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.CharField(default="../img/default.jpg", max_length=1000),
        ),
        migrations.AddField(
            model_name="listing",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="liked_listings", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(),
        ),
    ]
