# Generated by Django 5.0.7 on 2024-07-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_listing_adults_remove_listing_check_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="adults",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="check_in",
            field=models.CharField(default="01/01/2025", max_length=10),
        ),
        migrations.AddField(
            model_name="listing",
            name="check_out",
            field=models.CharField(default="01/01/2025", max_length=10),
        ),
        migrations.AddField(
            model_name="listing",
            name="children",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="infants",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="pets",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
